# Generated by Django 4.2.6 on 2023-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('vendor', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('tags', models.TextField()),
            ],
        ),
    ]
