# Generated by Django 4.1.12 on 2023-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='featured_image',
            field=models.TextField(),
        ),
    ]
